# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://git.ontariogovernment.ca/service-integration/team-tools/pre-commit
    rev: 2ae64e6309654d76e11aa204e558b3820b1b0046
    hooks:
      - id: npm-run-test
        always_run: true
        stages: [commit]
      - id: npm-run-lint
        always_run: true
        stages: [commit]
      - id: npm-run-format-code
        always_run: true
        stages: [commit]
      - id: check-whitespace
        always_run: true
        stages: [commit]
      - id: add-jira-ref
        always_run: true
        stages: [prepare-commit-msg]
